export const outfitRecommendations = [
  {
    id: "happy-party",
    mood: "happy",
    event: "party",
    moodLabel: "Happy",
    eventLabel: "Party",
    title: "Vibrant Party Ensemble",
    description: "A colorful and energetic outfit that reflects your happy mood and is perfect for a party setting.",
    imageUrl: "/happyparty.jpeg",
    items: [
      "Bright colored dress or patterned shirt",
      "Statement accessories (chunky necklace or bold earrings)",
      "Comfortable yet stylish dancing shoes",
      "Small crossbody bag or clutch",
    ],
    styleTips:
      "Don't be afraid to mix patterns and colors when you're feeling happy! Add a bright lipstick to complete the look.",
  },
  {
    id: "happy-meeting",
    mood: "happy",
    event: "meeting",
    moodLabel: "Happy",
    eventLabel: "Meeting",
    title: "Cheerful Professional Attire",
    description:
      "A polished yet upbeat outfit that brings positive energy to your meeting while maintaining professionalism.",
    imageUrl: "/happymeeting.jpeg",
    items: [
      "Colorful blazer or cardigan in a cheerful tone",
      "Crisp white or light-colored shirt",
      "Well-fitted trousers or knee-length skirt",
      "Comfortable yet professional shoes",
      "Subtle yet cheerful accessories",
    ],
    styleTips:
      "Incorporate color through your blazer or accessories while keeping the overall look professional. A bright smile is your best accessory!",
  },
  {
    id: "happy-date",
    mood: "happy",
    event: "date",
    moodLabel: "Happy",
    eventLabel: "Date",
    title: "Joyful Date Look",
    description:
      "A playful and cheerful outfit that expresses your happy mood and creates a positive atmosphere for your date.",
    imageUrl: "/happydate.jpeg",
    items: [
      "Flowy sundress or colorful casual shirt",
      "Light wash jeans or casual skirt",
      "Comfortable yet stylish shoes",
      "Playful accessories that showcase your personality",
      "Light jacket or cardigan for cooler evenings",
    ],
    styleTips:
      "Let your happy mood shine through with colors and patterns that make you smile. Your date will appreciate your authentic joy!",
  },
  {
    id: "happy-workout",
    mood: "happy",
    event: "workout",
    moodLabel: "Happy",
    eventLabel: "Workout",
    title: "Energetic Fitness Attire",
    description:
      "A bright and motivating workout outfit that channels your happy energy into an effective exercise session.",
    imageUrl: "/happyworkout.jpeg",
    items: [
      "Brightly colored or patterned workout top",
      "Comfortable, well-fitted athletic shorts or leggings",
      "Supportive athletic shoes in a fun color",
      "Sweatband or hair tie in a complementary color",
      "Motivational fitness tracker or accessories",
    ],
    styleTips:
      "Bright colors can boost your mood even further during your workout. Choose moisture-wicking fabrics that keep you comfortable while you exercise.",
  },
  {
    id: "happy-formal",
    mood: "happy",
    event: "formal",
    moodLabel: "Happy",
    eventLabel: "Formal Event",
    title: "Elegant Celebratory Attire",
    description:
      "A sophisticated yet joyful formal outfit that expresses your happy mood while respecting the event's formality.",
    imageUrl: "/happyformal.jpeg",
    items: [
      "Elegant dress or suit in a vibrant yet appropriate color",
      "Refined accessories with a touch of personality",
      "Polished formal shoes",
      "Statement piece of jewelry or accessory",
      "Elegant clutch or small formal bag",
    ],
    styleTips:
      "Express your happy mood through subtle pops of color or unique accessories while maintaining the formal dress code. Your genuine smile will be your best accessory.",
  },
  {
    id: "happy-casual",
    mood: "happy",
    event: "casual",
    moodLabel: "Happy",
    eventLabel: "Casual Outing",
    title: "Cheerful Casual Ensemble",
    description: "A bright, uplifting outfit that expresses your happy mood during a casual day out.",
    imageUrl: "/happycasual.jpeg",
    items: [
      "Colorful top or t-shirt with a fun print",
      "Comfortable jeans or casual skirt",
      "White sneakers or sandals",
      "Playful accessories (colorful bag, fun earrings)",
      "Light jacket or cardigan",
    ],
    styleTips: "Don't be afraid to mix colors that make you happy! A bright accessory can lift even a simple outfit.",
  },
  {
    id: "confident-meeting",
    mood: "confident",
    event: "meeting",
    moodLabel: "Confident",
    eventLabel: "Meeting",
    title: "Power Professional Look",
    description: "A sharp, authoritative outfit that projects confidence and competence in a meeting environment.",
    imageUrl: "/confidentmeeting.jpeg",
    items: [
      "Well-tailored blazer in a bold color",
      "Crisp white or light blue button-up shirt",
      "Tailored trousers or pencil skirt",
      "Polished leather shoes or heels",
      "Minimal, elegant accessories",
    ],
    styleTips:
      "Posture is key with this outfit. Stand tall, shoulders back, and make eye contact to maximize your confident appearance.",
  },
  {
    id: "confident-party",
    mood: "confident",
    event: "party",
    moodLabel: "Confident",
    eventLabel: "Party",
    title: "Bold Statement Party Look",
    description: "A striking outfit that commands attention and showcases your confidence in a party setting.",
    imageUrl: "/confidentpartyyy.jpeg",
    items: [
      "Statement piece (leather jacket, bold dress, or eye-catching top)",
      "Well-fitted jeans, trousers, or skirt that accentuates your best features",
      "Standout shoes that are both comfortable and stylish",
      "Bold accessories that complement without overwhelming",
      "Signature fragrance that leaves an impression",
    ],
    styleTips:
      "Choose one statement piece and build your outfit around it. Your confidence will shine through when you feel comfortable yet striking in what you're wearing.",
  },
  {
    id: "confident-casual",
    mood: "confident",
    event: "casual",
    moodLabel: "Confident",
    eventLabel: "Casual Outing",
    title: "Effortlessly Assured Casual Look",
    description: "A polished yet relaxed outfit that exudes confidence while maintaining casual comfort.",
    imageUrl: "/confidentcasual.jpeg",
    items: [
      "Well-fitted premium t-shirt or casual button-up",
      "Quality jeans or chinos in a flattering cut",
      "Clean, stylish sneakers or casual leather shoes",
      "Minimal yet quality accessories (watch, simple jewelry)",
      "Light jacket or overshirt that elevates the look",
    ],
    styleTips:
      "Focus on fit and quality rather than flashy elements. Well-fitted basics in premium materials will project confidence more than trendy pieces that don't suit you.",
  },
  {
    id: "confident-workout",
    mood: "confident",
    event: "workout",
    moodLabel: "Confident",
    eventLabel: "Workout",
    title: "Performance-Focused Fitness Attire",
    description:
      "A sleek, functional workout outfit that helps you feel powerful and capable during your exercise routine.",
    imageUrl: "/confidentworkout.jpeg",
    items: [
      "High-performance athletic wear in bold, solid colors",
      "Compression elements that provide support and highlight your physique",
      "Quality athletic shoes appropriate for your workout type",
      "Minimal but functional accessories (fitness watch, quality headphones)",
      "Sweat-wicking headband or cap (if needed)",
    ],
    styleTips:
      "Choose athletic wear that fits well and makes you feel strong. Solid colors in black, navy, or deep red can project confidence and focus.",
  },
  {
    id: "confident-date",
    mood: "confident",
    event: "date",
    moodLabel: "Confident",
    eventLabel: "Date",
    title: "Bold Impression Date Look",
    description: "A striking outfit that showcases your confidence and makes a memorable impression on your date.",
    imageUrl: "/confidentdate.jpeg",
    items: [
      "Statement piece (bold jacket, distinctive shirt, or eye-catching dress)",
      "Well-fitted jeans or trousers",
      "Stylish yet comfortable shoes",
      "Signature accessory that reflects your personality",
      "Light, appealing fragrance",
    ],
    styleTips:
      "Wear something that makes you feel amazing - confidence is the most attractive feature. Choose one bold item and build your outfit around it.",
  },
  {
    id: "confident-formal",
    mood: "confident",
    event: "formal",
    moodLabel: "Confident",
    eventLabel: "Formal Event",
    title: "Commanding Formal Presence",
    description:
      "A sophisticated formal outfit that commands respect and attention while maintaining appropriate elegance.",
    imageUrl: "/confidentformal.jpeg",
    items: [
      "Impeccably tailored suit or elegant formal dress in a power color",
      "Quality dress shirt or complementary top",
      "Polished formal shoes that combine comfort and style",
      "Minimal yet striking accessories (cufflinks, statement jewelry)",
      "Classic watch or elegant bracelet",
    ],
    styleTips:
      "Focus on impeccable fit and quality materials. A well-tailored outfit in a classic cut will project more confidence than trendy formal wear that doesn't suit your body type.",
  },
  {
    id: "chill-casual",
    mood: "chill",
    event: "casual",
    moodLabel: "Chill",
    eventLabel: "Casual Outing",
    title: "Effortless Casual Comfort",
    description: "A relaxed yet put-together look that's perfect for a laid-back day out while feeling chill.",
    imageUrl: "/chillcasual.jpeg",
    items: [
      "Oversized sweater or soft hoodie",
      "High-waisted jeans or joggers",
      "White sneakers or comfortable boots",
      "Beanie or baseball cap (optional)",
      "Crossbody bag or backpack",
    ],
    styleTips:
      "Layer for both comfort and style. A simple necklace or watch can elevate this casual look without sacrificing the relaxed vibe.",
  },
  {
    id: "chill-party",
    mood: "chill",
    event: "party",
    moodLabel: "Chill",
    eventLabel: "Party",
    title: "Laid-Back Party Style",
    description:
      "A relaxed yet stylish outfit that keeps you comfortable while still looking appropriate for a party setting.",
    imageUrl: "/chillparty.jpeg",
    items: [
      "Relaxed-fit button-up shirt or comfortable stylish top",
      "Well-worn but clean jeans or relaxed trousers",
      "Comfortable yet presentable shoes (clean sneakers or casual boots)",
      "Minimal accessories that add personality without fuss",
      "Light jacket or overshirt for layering",
    ],
    styleTips:
      "Aim for the sweet spot between comfort and style. Choose pieces that don't restrict movement but still look intentional rather than thrown together.",
  },
  {
    id: "chill-meeting",
    mood: "chill",
    event: "meeting",
    moodLabel: "Chill",
    eventLabel: "Meeting",
    title: "Relaxed Professional Attire",
    description: "A comfortable yet appropriate outfit that projects calm competence in a meeting environment.",
    imageUrl: "/chillmeeting.jpeg",
    items: [
      "Unstructured blazer or comfortable cardigan",
      "Soft button-up or quality t-shirt in a solid color",
      "Relaxed-fit chinos or comfortable dress pants",
      "Loafers or comfortable yet professional shoes",
      "Minimal accessories that add polish without fuss",
    ],
    styleTips:
      "Choose clothes in natural fabrics that breathe well. Soft cotton, linen blends, or light wool will keep you comfortable while still looking professional.",
  },
  {
    id: "chill-date",
    mood: "chill",
    event: "date",
    moodLabel: "Chill",
    eventLabel: "Date",
    title: "Relaxed Date Ensemble",
    description:
      "A comfortable yet thoughtful outfit that creates a relaxed atmosphere for your date while still showing you made an effort.",
    imageUrl: "/chilldate.jpeg",
    items: [
      "Soft, well-fitted t-shirt or casual button-up",
      "Favorite jeans or casual pants in good condition",
      "Clean, comfortable sneakers or casual shoes",
      "Light jacket, cardigan, or flannel for layering",
      "One simple accessory that has personal meaning",
    ],
    styleTips:
      "Choose clothes that you already know feel good and look good on you. Your date will appreciate your authentic, relaxed self more than an uncomfortable attempt at dressing up.",
  },
  {
    id: "chill-workout",
    mood: "chill",
    event: "workout",
    moodLabel: "Chill",
    eventLabel: "Workout",
    title: "Comfortable Fitness Attire",
    description:
      "A relaxed workout outfit that prioritizes comfort while still providing the functionality needed for exercise.",
    imageUrl: "/chillworkout.jpeg",
    items: [
      "Soft, loose-fitting t-shirt or tank top",
      "Comfortable athletic shorts or joggers",
      "Well-cushioned athletic shoes appropriate for your activity",
      "Lightweight, breathable socks",
      "Simple headband or hair tie if needed",
    ],
    styleTips:
      "Choose athletic wear that doesn't restrict or irritate. Comfort will help you maintain a relaxed state of mind throughout your workout.",
  },
  {
    id: "chill-formal",
    mood: "chill",
    event: "formal",
    moodLabel: "Chill",
    eventLabel: "Formal Event",
    title: "Relaxed Formal Elegance",
    description:
      "A comfortable yet appropriate formal outfit that allows you to remain relaxed while meeting the event's dress code.",
    imageUrl: "/chillformal.jpeg",
    items: [
      "Comfortable formal wear in breathable fabrics",
      "Slightly relaxed-fit dress shirt or elegant but non-restrictive top",
      "Well-fitted but not tight formal pants or skirt",
      "Broken-in formal shoes that won't pinch or cause discomfort",
      "Minimal accessories that meet formal requirements without feeling excessive",
    ],
    styleTips:
      "Look for formal wear with a bit of stretch or in natural fibers. Consider slightly more relaxed cuts while maintaining appropriate formality through quality and color choices.",
  },
  {
    id: "sad-casual",
    mood: "sad",
    event: "casual",
    moodLabel: "Sad",
    eventLabel: "Casual Outing",
    title: "Comfort-First Casual",
    description:
      "A soft, comforting outfit that provides emotional support while still looking put-together for a casual outing.",
    imageUrl: "/sadcasual.jpeg",
    items: [
      "Favorite oversized cardigan or comfort sweater",
      "Soft t-shirt in a calming color",
      "Well-worn jeans or comfortable pants",
      "Slip-on shoes or favorite sneakers",
      "Comforting accessory (special necklace, bracelet)",
    ],
    styleTips:
      "Choose fabrics that feel good against your skin. Soft textures can provide sensory comfort when you're feeling down.",
  },
  {
    id: "sad-party",
    mood: "sad",
    event: "party",
    moodLabel: "Sad",
    eventLabel: "Party",
    title: "Mood-Lifting Party Attire",
    description:
      "A comfortable yet appropriate party outfit that might help lift your spirits while respecting your current emotional state.",
    imageUrl: "/sadparty.jpeg",
    items: [
      "Comfortable yet presentable dark jeans or pants",
      "Soft, quality top in a neutral or dark color",
      "Layer with a favorite jacket or cardigan that feels like armor",
      "Comfortable shoes that won't add to your discomfort",
      "One special accessory that has positive associations or memories",
    ],
    styleTips:
      "Don't force yourself into uncomfortable 'party clothes' when you're feeling down. Choose items that feel like a comfort blanket but still look intentional.",
  },
  {
    id: "sad-meeting",
    mood: "sad",
    event: "meeting",
    moodLabel: "Sad",
    eventLabel: "Meeting",
    title: "Protective Professional Attire",
    description:
      "A professional outfit that provides emotional comfort and a sense of protection while maintaining appropriate workplace appearance.",
    imageUrl: "/sadmeeting.jpeg",
    items: [
      "Comfortable blazer or cardigan in a darker, calming tone",
      "Soft, non-restrictive shirt in a simple pattern or solid color",
      "Well-fitted but comfortable trousers or skirt",
      "Familiar, broken-in professional shoes",
      "Minimal accessories that have personal meaning or comfort value",
    ],
    styleTips:
      "Choose clothes that feel like armor - protective layers that give you confidence while respecting your need for emotional comfort. Darker colors can help you feel less exposed.",
  },
  {
    id: "sad-date",
    mood: "sad",
    event: "date",
    moodLabel: "Sad",
    eventLabel: "Date",
    title: "Authentic Comfort Date Look",
    description:
      "A thoughtful outfit that honors your emotional state while still showing care for your appearance and the date occasion.",
    imageUrl: "/saddate.jpeg",
    items: [
      "Favorite comfortable shirt or top that still looks presentable",
      "Well-fitted jeans or pants that don't restrict",
      "Comfortable yet nice shoes that don't require breaking in",
      "Soft scarf or light jacket that can serve as comfort",
      "One meaningful accessory that might lift your spirits",
    ],
    styleTips:
      "Be authentic about your mood rather than forcing excessive cheerfulness. Choose clothes that feel good physically and emotionally while still showing you value the date enough to make an effort.",
  },
  {
    id: "sad-workout",
    mood: "sad",
    event: "workout",
    moodLabel: "Sad",
    eventLabel: "Workout",
    title: "Gentle Movement Attire",
    description: "A soft, non-restrictive workout outfit that encourages gentle movement to help process emotions.",
    imageUrl: "/sadworkout.jpeg",
    items: [
      "Soft, loose-fitting t-shirt or long-sleeve top",
      "Comfortable joggers or loose workout pants",
      "Well-cushioned, supportive athletic shoes",
      "Warm, cozy socks",
      "Comforting hoodie or jacket for before and after",
    ],
    styleTips:
      "Choose clothes that feel like a gentle hug. Exercise can help with sadness, but your workout clothes should support gentle movement rather than intense training when you're feeling down.",
  },
  {
    id: "sad-formal",
    mood: "sad",
    event: "formal",
    moodLabel: "Sad",
    eventLabel: "Formal Event",
    title: "Dignified Comfort Formal Wear",
    description: "A formal outfit that provides emotional protection while meeting social obligations with dignity.",
    imageUrl: "/sadformal.jpeg",
    items: [
      "Well-fitted but not tight formal attire in a darker color",
      "Soft, quality fabrics that feel good against the skin",
      "Comfortable formal shoes that have been worn before",
      "Minimal, meaningful accessories that provide emotional comfort",
      "Layer with a quality jacket, wrap, or cardigan that feels protective",
    ],
    styleTips:
      "Choose formal wear that doesn't add physical discomfort to emotional distress. Dark colors can help you feel less visible while still looking appropriate. Quality over quantity - a few well-chosen pieces will serve better than complicated outfits.",
  },
  {
    id: "energetic-workout",
    mood: "energetic",
    event: "workout",
    moodLabel: "Energetic",
    eventLabel: "Workout",
    title: "High-Performance Activewear",
    description: "A functional, motivating outfit that channels your energy into an effective workout session.",
    imageUrl: "/energeticworkout.jpeg",
    items: [
      "Moisture-wicking athletic top in a bright color",
      "Supportive leggings or shorts",
      "Proper athletic shoes for your workout type",
      "Sweatband or hat (if needed)",
      "Lightweight, hands-free bag for essentials",
    ],
    styleTips:
      "Bright colors can help maintain your energetic mood. Make sure everything fits well and doesn't restrict movement during your workout.",
  },
  {
    id: "energetic-party",
    mood: "energetic",
    event: "party",
    moodLabel: "Energetic",
    eventLabel: "Party",
    title: "Dynamic Party Ensemble",
    description:
      "A vibrant, movement-friendly outfit that expresses your energetic mood and is perfect for dancing and socializing.",
    imageUrl: "/enegeticpartyy.jpeg",
    items: [
      "Bold, eye-catching top or dress in vibrant colors",
      "Comfortable yet stylish pants or skirt that allows movement",
      "Shoes you can dance in for hours",
      "Fun, statement accessories that catch the light",
      "Minimal bag that won't weigh you down",
    ],
    styleTips:
      "Choose clothes that allow you to move freely and express your energy. Bright colors and interesting textures can reflect your dynamic mood.",
  },
  {
    id: "energetic-meeting",
    mood: "energetic",
    event: "meeting",
    moodLabel: "Energetic",
    eventLabel: "Meeting",
    title: "Dynamic Professional Attire",
    description:
      "A polished yet energizing outfit that channels your enthusiasm into productive professional engagement.",
    imageUrl: "/energeticmeeting.jpeg",
    items: [
      "Crisp, well-fitted shirt or blouse in a vibrant yet professional color",
      "Tailored pants or skirt with perfect fit",
      "Comfortable yet professional shoes you can confidently move in",
      "One statement accessory that adds personality without distraction",
      "Structured bag or portfolio that organizes essentials efficiently",
    ],
    styleTips:
      "Channel your energy through one bold color piece while keeping the rest professional. Your energetic presence will be an asset if it's balanced with professional polish.",
  },
  {
    id: "energetic-date",
    mood: "energetic",
    event: "date",
    moodLabel: "Energetic",
    eventLabel: "Date",
    title: "Vibrant Date Look",
    description:
      "A lively, engaging outfit that expresses your energetic personality while creating a memorable impression.",
    imageUrl: "/energeticdate.jpeg",
    items: [
      "Colorful or interestingly textured top that starts conversations",
      "Well-fitted jeans or pants that allow comfortable movement",
      "Stylish yet comfortable shoes for spontaneous activities",
      "Playful accessories that showcase your personality",
      "Light jacket or layer that can adapt to changing plans",
    ],
    styleTips:
      "Your energy is attractive - let your outfit complement rather than compete with it. Choose clothes that can transition between activities since your energetic mood might lead to spontaneous plans.",
  },
  {
    id: "energetic-casual",
    mood: "energetic",
    event: "casual",
    moodLabel: "Energetic",
    eventLabel: "Casual Outing",
    title: "Dynamic Casual Ensemble",
    description: "A spirited, movement-friendly outfit perfect for an active day out while feeling energetic.",
    imageUrl: "/energeticcasual.jpeg",
    items: [
      "Bright, comfortable t-shirt or light sweater",
      "Well-fitted jeans or casual pants with stretch",
      "Comfortable sneakers or shoes you can walk miles in",
      "Lightweight backpack or crossbody bag for essentials",
      "Cap or sunglasses for outdoor activities",
    ],
    styleTips:
      "Choose clothes that won't restrict your movement or energy. Layers are key so you can adjust as your activity level changes throughout the day.",
  },
  {
    id: "energetic-formal",
    mood: "energetic",
    event: "formal",
    moodLabel: "Energetic",
    eventLabel: "Formal Event",
    title: "Vibrant Formal Attire",
    description:
      "A refined yet dynamic formal outfit that expresses your energetic personality while respecting the event's formality.",
    imageUrl: "/energeticformal.jpeg",
    items: [
      "Well-tailored formal attire with one vibrant element",
      "Crisp, quality formal shirt or complementary top",
      "Comfortable yet elegant formal shoes you can stand and move in",
      "Statement accessory that adds personality within formal boundaries",
      "Elegant watch or timepiece to keep track of your busy evening",
    ],
    styleTips:
      "Express your energy through one bold element - perhaps a colorful pocket square, statement jewelry, or unexpected formal shoe. Keep the rest classic to balance your natural exuberance with the event's formality.",
  },
  {
    id: "romantic-date",
    mood: "romantic",
    event: "date",
    moodLabel: "Romantic",
    eventLabel: "Date",
    title: "Enchanting Date Night Look",
    description:
      "A softly alluring outfit that enhances your romantic mood and creates a memorable impression for your date.",
    imageUrl: "/romanticdate.jpeg",
    items: [
      "Flowy dress or well-fitted button-up shirt",
      "Subtle fragrance",
      "Elegant watch or delicate jewelry",
      "Polished shoes or heels you can comfortably walk in",
      "Light jacket or blazer",
    ],
    styleTips:
      "Choose one feature to highlight - if you're wearing a bold top, keep the bottom simple. Balance is key to a romantic look that isn't overwhelming.",
  },
  {
    id: "romantic-party",
    mood: "romantic",
    event: "party",
    moodLabel: "Romantic",
    eventLabel: "Party",
    title: "Dreamy Party Ensemble",
    description:
      "A softly captivating outfit that expresses your romantic mood while being appropriate for a party setting.",
    imageUrl: "/romanticparty.jpeg",
    items: [
      "Flowing top or dress in a soft, flattering color",
      "Well-fitted pants or skirt that creates an elegant silhouette",
      "Comfortable yet elegant shoes that complement the outfit",
      "Delicate jewelry or accessories that catch the light",
      "Light perfume or cologne that leaves a subtle impression",
    ],
    styleTips:
      "Focus on soft textures and flowing silhouettes. Choose fabrics that move beautifully when you walk or dance to create a dreamy effect.",
  },
  {
    id: "romantic-meeting",
    mood: "romantic",
    event: "meeting",
    moodLabel: "Romantic",
    eventLabel: "Meeting",
    title: "Softly Professional Attire",
    description:
      "A gentle yet professional outfit that channels your romantic mood into a polished workplace appearance.",
    imageUrl: "/romanticmeeting.jpeg",
    items: [
      "Softly tailored blazer or cardigan in a muted, elegant tone",
      "Silk or soft cotton blouse or shirt",
      "Well-fitted trousers or knee-length skirt",
      "Polished yet comfortable shoes in a neutral tone",
      "Subtle, elegant accessories that add refinement without distraction",
    ],
    styleTips:
      "Channel your romantic mood through soft fabrics and flowing silhouettes while maintaining professional boundaries. Soft colors like blush, lavender, or muted blue can express romanticism while remaining workplace-appropriate.",
  },
  {
    id: "romantic-casual",
    mood: "romantic",
    event: "casual",
    moodLabel: "Romantic",
    eventLabel: "Casual Outing",
    title: "Romantic Casual Look",
    description: "A soft and romantic outfit perfect for a casual day out.",
    imageUrl: "/romanticcasual.jpeg",
    items: [
      "Soft, flowy blouse or sweater",
      "Light wash jeans or casual skirt",
      "Comfortable flats or sandals",
      "Delicate jewelry",
      "Light cardigan or jacket",
    ],
    styleTips: "Choose soft, romantic colors and fabrics that make you feel beautiful and comfortable.",
  },
  {
    id: "romantic-workout",
    mood: "romantic",
    event: "workout",
    moodLabel: "Romantic",
    eventLabel: "Workout",
    title: "Romantic Fitness Attire",
    description: "A soft and feminine workout outfit that keeps you comfortable while exercising.",
    imageUrl: "/romanticworkout.jpeg",
    items: [
      "Soft, pastel-colored workout top",
      "Comfortable leggings or shorts",
      "Supportive athletic shoes",
      "Soft headband or hair tie",
      "Light, breathable jacket",
    ],
    styleTips: "Choose soft, romantic colors and comfortable fabrics that make you feel good while working out.",
  },
  {
    id: "romantic-formal",
    mood: "romantic",
    event: "formal",
    moodLabel: "Romantic",
    eventLabel: "Formal Event",
    title: "Enchanting Formal Elegance",
    description:
      "A dreamy, sophisticated formal outfit that expresses your romantic mood while meeting the event's formal requirements.",
    imageUrl: "/romanticformal.jpeg",
    items: [
      "Flowing gown or well-tailored suit in a soft, elegant color",
      "Quality fabrics with beautiful drape and movement",
      "Refined formal shoes that complement without overwhelming",
      "Elegant, subtle jewelry that catches the light",
      "Classic evening bag or clutch with romantic details",
    ],
    styleTips:
      "Focus on flowing silhouettes and fabrics that move beautifully. Soft colors like blush, champagne, or dusty blue can express your romantic mood while still being formal. Let the details—like delicate beading or gentle draping—tell the romantic story.",
  },
]
